"""Add user_profiles table

Revision ID: 3cb95f230574
Revises: 9a2a79e49c5c
Create Date: 2025-12-20 13:21:11.142414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb95f230574'
down_revision: Union[str, Sequence[str], None] = '9a2a79e49c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=120), nullable=False),
    sa.Column('days_per_week', sa.String(length=12), nullable=False),
    sa.Column('experience_level', sa.String(length=60), nullable=False),
    sa.Column('equipment_access', postgresql.ARRAY(sa.String(length=90)), nullable=False),
    sa.Column('session_length', sa.String(length=12), nullable=False),
    sa.Column('injuries', postgresql.ARRAY(sa.String(length=90)), nullable=False),
    sa.Column('sports_background', postgresql.ARRAY(sa.String(length=90)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
