"""Add onboarding_completed_at column in UserProfile table

Revision ID: 8078e68036da
Revises: 3cb95f230574
Create Date: 2025-12-20 18:01:09.513199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8078e68036da'
down_revision: Union[str, Sequence[str], None] = '3cb95f230574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'onboarding_completed_at')
    # ### end Alembic commands ###
